### ISSUE TITLE
GUI: Wrong output for case position

### ISSUE THREAD

**Issue by Shaac** [prologin/prologin2014#10]
> ###### Originally posted 2014-05-07 14:47 by [Shaac](https://bitbucket.org/Shaac/) on Bitbucket

When one clicks on a case and see its position, the second coordinate is always 15.

**Comment by pmderodat** [comment]
> ###### Originally posted 2014-05-07 21:23 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

gui: fix the vertical coordinate for cells in the details widget

Fix bug #10

This bug was introduced recently due to variable names aliasing.


→ <<cset 2642a9239d51>>

**Comment by pmderodat** [comment]
> ###### Originally posted 2014-05-11 11:43 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

gui: fix the vertical coordinate for cells in the details widget

Fix bug #10

This bug was introduced recently due to variable names aliasing.


→ <<cset f10005b5bea7>>
