### ISSUE TITLE
Overflow cout portee

### ISSUE THREAD

**Issue by ejls** [prologin/prologin2014#13]
> ###### Originally posted 2014-05-07 18:09 by [ejls](https://bitbucket.org/ejls/) on Bitbucket

ca devrait etre une quadratique, c'est une exponentielle actuellement
En plus le double est convertie en int, resultat, il est possible de set la portee tel que le cout est negatif (on gagne de l'argent) et la portee est toute la map.

**Comment by pmderodat** [comment]
> ###### Originally posted 2014-05-08 02:31 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

Est-ce que tu comptes travailler dessus ? Si non, est-ce que tu as demandé à quelqu’un de s’en occuper ?

**Comment by seirl** [comment]
> ###### Originally posted 2015-03-22 16:44 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Fixed by f3c097e
