### ISSUE TITLE
Plusieurs units assiegent une meme tourelle

### ISSUE THREAD

**Issue by ejls** [prologin/prologin2014#14]
> ###### Originally posted 2014-05-07 18:44 by [ejls](https://bitbucket.org/ejls/) on Bitbucket

Qui gagne MAGIE_TOURELLE ?

**Comment by bakablue** [comment]
> ###### Originally posted 2014-05-07 22:54 by [bakablue](https://bitbucket.org/bakablue/) on Bitbucket

Fixes #14 (supression of MAGIE_TOURELLE


→ <<cset 49d0353d4d10>>

**Comment by pmderodat** [comment]
> ###### Originally posted 2014-05-11 11:43 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

Fixes #14 (supression of MAGIE_TOURELLE


→ <<cset 36223b213358>>
