### ISSUE TITLE
Wizards attacking a tower

### ISSUE THREAD

**Issue by bakablue** [prologin/prologin2014#15]
> ###### Originally posted 2014-05-07 20:38 by [bakablue](https://bitbucket.org/bakablue/) on Bitbucket

A wizard should be able to attack only one tower every turn.

**Comment by bakablue** [comment]
> ###### Originally posted 2014-05-07 22:31 by [bakablue](https://bitbucket.org/bakablue/) on Bitbucket

Implements #14 fixes #15


→ <<cset 29893d3d9920>>

**Comment by pmderodat** [comment]
> ###### Originally posted 2014-05-11 11:43 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

Implements #14 fixes #15


→ <<cset 5a5980daf921>>
