### ISSUE TITLE
Cancel

### ISSUE THREAD

**Issue by bakablue** [prologin/prologin2014#17]
> ###### Originally posted 2014-05-08 01:41 by [bakablue](https://bitbucket.org/bakablue/) on Bitbucket

We have to test the cancel action.

**Comment by pmderodat** [comment]
> ###### Originally posted 2014-05-08 02:33 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

Giving it a try…

**Comment by pmderodat** [comment]
> ###### Originally posted 2014-05-10 20:17 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

The contest is over, so not useful anymore.
