### ISSUE TITLE
Players can still play when their base is lost

### ISSUE THREAD

**Issue by pmderodat** [prologin/prologin2014#19]
> ###### Originally posted 2014-05-08 04:22 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

Have a look at the first player with the attached IA (used for all four players): it looses its base quite soon, but still continue to create wizards and to move them.

Players are not supposed to be able to do anything when their base is lost.

**Comment by bakablue** [comment]
> ###### Originally posted 2014-05-08 06:35 by [bakablue](https://bitbucket.org/bakablue/) on Bitbucket

Recode resolve_fights, fixes #19


→ <<cset 4401ea36f73b>>

**Comment by pmderodat** [comment]
> ###### Originally posted 2014-05-11 11:43 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

Recode resolve_fights, fixes #19


→ <<cset 6d3e2438d8da>>
