### ISSUE TITLE
Wrong phase received by the gui and the dumper

### ISSUE THREAD

**Issue by bakablue** [prologin/prologin2014#5]
> ###### Originally posted 2014-05-06 17:22 by [bakablue](https://bitbucket.org/bakablue/) on Bitbucket

From a spectator's point of view, the move phase is the first one.

**Comment by seirl** [comment]
> ###### Originally posted 2014-05-07 01:03 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Solved by https://github.com/prologin/stechec2/commit/a72b18553430c5fec4ecfc19c74bf5625f3e9328
